// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StudentEquipBorrowSystem.Infrastructure.Migrations
{
    [DbContext(typeof(EquipmentBorrowingDbContext))]
    [Migration("20261004121055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Domain.Borrow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("BorrowDate");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("DueDate");

                    b.Property<Guid>("EquipmentBorrowed_Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReturnDate");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("StudentBorrower_StudentID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Borrows_Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Borrows_DueDate");

                    b.HasIndex("EquipmentBorrowed_Id")
                        .HasDatabaseName("IX_Borrows_EquipmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Borrows_Status");

                    b.HasIndex("StudentBorrower_StudentID")
                        .HasDatabaseName("IX_Borrows_StudentID");

                    b.ToTable("Borrows", (string)null);
                });

            modelBuilder.Entity("Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("EquipmentName");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EquipmentType");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("IsAvailable");

                    b.HasKey("Id")
                        .HasName("PK_Equipment_Id");

                    b.HasIndex("EquipmentType")
                        .HasDatabaseName("IX_Equipment_EquipmentType");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Equipment_IsAvailable");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("Domain.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("StudentID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("College");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("ContactNumber");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Course");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("FullName");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("YearLevel");

                    b.HasKey("StudentID")
                        .HasName("PK_Students_StudentID");

                    b.HasIndex("ContactNumber")
                        .HasDatabaseName("IX_Students_ContactNumber");

                    b.HasIndex("StudentID")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_StudentID_Unique");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Domain.Borrow", b =>
                {
                    b.HasOne("Domain.Equipment", "EquipmentBorrowed")
                        .WithMany()
                        .HasForeignKey("EquipmentBorrowed_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Borrows_Equipment_Id");

                    b.HasOne("Domain.Student", "StudentBorrower")
                        .WithMany()
                        .HasForeignKey("StudentBorrower_StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Borrows_Students_StudentID");

                    b.Navigation("EquipmentBorrowed");

                    b.Navigation("StudentBorrower");
                });
#pragma warning restore 612, 618
        }
    }
}
